### ISSUE TITLE
Compatibility with Celestial Exploration workbench recipes

### ISSUE THREAD

**Issue by shazean** [sweetrpg/CraftTracker#14]
Please add compatibility with Celestial Exploration workbench recipes.

**Comment by paulyhedral** [comment]
@shazean This might be an issue with CE, since
```
        CTPlugin.jeiRuntime.getIngredientListOverlay().getIngredientUnderMouse()
```
returns an empty Optional when trying to queue, for example, spacesuit leggings.

**Comment by paulyhedral** [comment]
Appears to be fixed by another unrelated bug fix.
