### ISSUE TITLE
Queue Manager GUI missing bottom pixels

### ISSUE THREAD

**Issue by shazean** [sweetrpg/CraftTracker#37]
In the queue manager, all of the buttons are missing the bottom few pixels.  When a button is highlighted, the bottom of the highlight is also missing.

**Comment by paulyhedral** [comment]
Fixed in:
- 1.16 (ecbf160a49b3ca44d2b04ff8d0d50c98a98dd009)
- 1.18 (c6397ce42e5887c16943b010f2dd1562f4c08eab)
- 1.19 (a64d30a5425e0ee1d6c24b2ec73d4ef83ceed502)
- 1.20 (b16a0746258ca992e9b09449c6caab9e26e77a91)
